### PR TITLE
Introduced pty_handler option on command

### PR DESCRIPTION
**Pull request by robd**
Allows custom strategy for handling interaction with pty to be specified per command. 

The INTERACTIVE_SUDO strategy handles capturing a sudo password from the user, caching and sending it to the remote server when requested

### CODE REVIEW

**Comment by robd** [comment]
I wrote a preliminary PR to implement this in sshkit here https://github.com/capistrano/sshkit/pull/234

**Comment by kentaroi** [comment]
Hi @robd !

This patch is a `per-command` part of the change you wrote in #2, isn't it?
And, it ignores `Netssh.config.pty`.
That seems to change the behaviour when a user `set :pty, true/false` in Capistrano.

https://github.com/capistrano/sshkit/pull/234 looks promising and you implemented it more completely there.
May I suggest that you close this PR and concentrate on https://github.com/capistrano/sshkit/pull/234?

Thank you,

**Comment by robd** [comment]
Yes you are completely right about the default pty behaviour, which I hadn't reinstated. As you say, things look promising over in https://github.com/capistrano/sshkit/pull/234, so closing this PR.

**Comment by kentaroi** [comment]
Thanks

**Pull request closed without merging**
